### PR TITLE
Remove the status endpoint

### PR DESCRIPTION
**Pull request by seanh**
This means that Pyramid is no longer needed, since the Pyramid app only served the status endpoint, so remove Pyramid as well.

This also means that there are no longer any tests since the status endpoint was the only part that had tests, but I left the test framework and dependencies in place in case we want to add some one day.

The status endpoint doesn't do anything for h-periodic, for a few reasons:

1. Elastic Load Balancing health checks just send an HTTP request to the configured health check path and consider the server healthy if it returns 200 OK, unhealthy otherwise.

   The JSON body with the `status` field and individual status information about each beat process and its connection to RabbitMQ is *not* used by Elastic Load Balancing.

   The JSON body can't easily be used by humans either, since h-periodic is not exposed to the internet. Nor would we want to expose h-periodic's status endpoint to the internet since hitting it consumes a non-trivial amount of resources.

   There's just no point in having all this code, and there's a maintenance cost to it, for example if I want to [disable the h beat on h-periodic-qa](https://github.com/hypothesis/h-periodic/pull/54) I'll have to update this status code which currently assumes that both beats are always wanted all the time.

   All a status endpoint should do is return 200 or 500, no body, since that's all that actually matters.

   If further information about the app's status is wanted for humans the status endpoint's responses aren't the place for that since they aren't accessible. Logging might be a better place.

   See: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.healthstatus.html#using-features.healthstatus.understanding

2. The endpoint is [coded to return 200 OK if _either_ of the beats (h or checkmate) is ok](https://github.com/hypothesis/h-periodic/blob/9e85310218f53fe8fa652b25111327d23b5b948b/h_periodic/views/status.py#L31-L36), but with `"status": "degraded"` in the JSON body if one of the beats is broken. Elastic Load Balancing would ignore this JSON body and just look at the 200 OK HTTP status and assume the app is healthy. _Both_ of the beats would have to be down at the same time in order for the status endpoint to return 500 and trigger a health alert. There is no concept of "degraded" in Elastic Load Balancing health checks, it's just either 200 OK or other. ("Degraded" in Elastic Beanstalk is a higher-level thing that it determines based on health check responses and other signals.)

3. The above points are both moot anyway because [health check URLs aren't supported at all for single-instance apps](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.healthstatus.html#monitoring-basic-healthcheck-singleinstance) like h-periodic: <q>In a single instance or worker tier environment, Elastic Beanstalk determines the instance's health by monitoring its Amazon EC2 instance status. Elastic Load Balancing health settings, including HTTP health check URLs, cannot be used in these environment types.</q>

   h-periodic uses EC2 instance status checks instead: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-system-instance-status-check.html

   I don't think these EC2 instance status checks allow us to plug into them in any way and change the status if the beat process isn't running or the RabbitMQ connection isn't working, like we're trying to do in `status.py`. I think if we want an alarm to go off if h-periodic isn't working, we're going to have to implement that in other ways:

   * The annotation sync queue reports metrics to New Relic and has New Relic alarms for if these metrics drop
   * Checkmate [needs to do the same](https://github.com/hypothesis/checkmate/issues/56)

### CODE REVIEW

**Comment by jon-betts** [comment]
So slack is dead which makes this all a bit awkward, but before we hoy all this in the bin, I feel like this is the sort of thing we are interested in, even if AWS isn't.

Knowing that AWS doesn't care if our box is doing anything, just that it's up feels a bit worrying. Some ideas that immediately pop out at me:

* Expose this publicly (maybe with a different name?) and poke it with pingdom or something similar
* A fancier more ops'y version of that
* Register these as New Relic custom metrics instead and report on it that way

Now we have the `DISABLE_H_BEAT` we can also make a sensible decision about whether we are down or not.

If we were to do any of the above, we'd probably want some of this code at least, but Pyramid feels like total overkill depending on the solution. If we just need to report back to New Relic, then we don't need a web framework at all.

**Comment by seanh** [comment]
I think the right solution here is for the _workers_ in h and checkmate to to trigger New Relic alarms if they stop working:

* Celery workers automatically appear as "transactions" in New Relic. These transactions get throughput graphs in New Relic. Set alarms on those throughput graphs. Doesn't require any custom metrics.
* Not necessary in most cases but workers can also post custom metrics to New Relic, such as the job completion rate and queue length etc that h's annotation sync task posts. We can (and are planning to) add New Relic alarms based on these metrics

That avoids the whole issue of checkmate having a status endpoint and also provides a more end-to-end test of the periodic tasks system.

* * *

I don't think we want to expose this endpoint publicly since calling it can make h-periodic do work, and if something sent a lot of requests it could do a lot of work. And I just don't think we want a public endpoint to maintain, it just opens up the potential for there to be issues such as security flaws or whatever, just gives us work to do.

Honestly my opinion is that we don't need this:

* There are better ways to make alarms go off if periodic tasks aren't working, as discussed above.

* There are better ways to debug h-periodic. You can't easily access the status endpoint currently (you'd have to ssh into something) and I don't think we want to make it public. If we want to know what's happening in h-periodic (e.g. what beat processes are up, what CloudAMQP connections are working) I think a better way is to look at h-periodic's logs in Papertrail, there should be log messages showing either that all is fine or that things aren't working.

* It's misleading as it makes it look like h-periodic actually has a status endpoint that AWS actually uses the same as our other apps

* I don't think we want to maintain this code


Here's a peek at what's in [h-periodic prod's logs](https://my.papertrailapp.com/groups/22067372/events) right now. These are very easy to access and make it immediately clear that things are working. If things were broken I suspect the logs would make that equally clear:

```
Jan 04 18:05:36 h-periodic-prod_... checkmate-beat (stderr) | [2021-01-04 18:05:36,699: INFO/MainProcess] Scheduler: Sending due task sync-blocklist (checkmate.async.tasks.sync_blocklist)
Jan 04 18:05:45 h-periodic-prod_... h-beat (stderr)      | [2021-01-04 18:05:45,580: INFO/MainProcess] Scheduler: Sending due task report-sync-annotations-queue-length (h.tasks.indexer.report_job_queue_metrics)
...
```

**Comment by jon-betts** [comment]
Yeah that's a pretty good idea and assuming it doesn't ruin everything, should be pretty easy to slap on. I think that's separate enough from this that we can just purge all of this as a separate task.

**Comment by jon-betts** [comment]
I've rebased this and made some fixes. I think as a result of `make sure` now running tests and things and few things have been uncovered:

* The readme still mentioned the health check end-point, so I scooped that out. 
* It also was very `h` centric, so I've mentioned `checkmate` too
* We need at least one test to get the tests passing
* The patch stuff is in `conftest.py` but not used. This seems reasonable to keep around, but I had to no-cover it.

It strikes me that even if we don't want to disable Checkmate, anyone other than us running this would. Not sure if that's a real class of people, or just imagined.

**Review by jon-betts — APPROVED** [review]
I've made some changes which you should review, but this looks good. It's also so skinny it makes me wonder about running a different `checkmate-periodic`. It's really only the beat file and some boilerplate now.

**Comment by jon-betts** [comment]
I've made some changes here which you should probably review, but I can't add you as a reviewer for some reason?

**Pull request merged**
